[pytest]

log_file = test.log
log_file_level = INFO
log_file_mode = w

markers =
    unit: pruebas unitarias
    functional: pruebas de requisitos funcionales
    nonfunctional: pruebas de requisitos no funcionales
    temperature: pruebas de conversiones de temperatura
    distance: pruebas de conversiones de distancia
    currency: pruebas de conversiones de moneda
    precision: pruebas de precisión de resultados
    input_integrity: pruebas de integridad de las entradas